import React from 'react'
import Profile from '../../components/profile'
import { getAllIds, getUserDataById } from '../../lib/users'
import Head from 'next/head'

const UserProfile = ({ userData }) => {
  const { firstName, lastName } = {...userData} || {}
  return (
    <>
      <Head>
        <title>{firstName} | {lastName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Profile {...{userData}}/>
    </>
  )
}

export const getStaticPaths = async () => {
  // const paths = await getAllIds()
  return {
    paths: [{params: {id: '1'}}],
    fallback: true
  }
}

export const getStaticProps = async ({ params }) => {
  const userData = await getUserDataById(params.id)
  return {
    props: {
      userData
    }
  }
}

export default UserProfile